site_name: Laboratório Maker - Jataí
site_description: Laboratório Maker da Universidade Federal de Jataí
site_author: LabMaker Jataí
site_url: https://labmaker-jatai.github.io/

theme:
  name: material
  language: pt
  palette:
    - scheme: default
      primary: deep orange
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    - scheme: slate
      primary: deep orange
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - Início: index.md
  - Sobre: sobre.md
  - Projetos: projetos.md
  - Equipamentos: equipamentos.md
  - Contato: contato.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
